/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.phunware.messages.avro;  
@SuppressWarnings("all")
public class LocalpointEventMsgAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LocalpointEventMsgAvro\",\"namespace\":\"com.phunware.messages.avro\",\"fields\":[{\"name\":\"tenant_id\",\"type\":[\"null\",\"long\"]},{\"name\":\"device_id\",\"type\":[\"null\",\"string\"]},{\"name\":\"device_id_type\",\"type\":[\"null\",\"string\"]},{\"name\":\"device_encoding_type\",\"type\":[\"null\",\"string\"]},{\"name\":\"store_id\",\"type\":[\"null\",\"long\"]},{\"name\":\"geofence_id\",\"type\":[\"null\",\"long\"]},{\"name\":\"device_date_time\",\"type\":[\"null\",\"string\"]},{\"name\":\"device_location_accuracy\",\"type\":[\"null\",\"double\"]},{\"name\":\"device_location_latitude\",\"type\":[\"null\",\"double\"]},{\"name\":\"device_location_longitude\",\"type\":[\"null\",\"double\"]},{\"name\":\"request\",\"type\":[\"null\",\"string\"]},{\"name\":\"response\",\"type\":[\"null\",\"string\"]},{\"name\":\"requestDate\",\"type\":[\"null\",\"string\"]},{\"name\":\"message_id\",\"type\":[\"null\",\"long\"]},{\"name\":\"push_notification_event_id\",\"type\":[\"null\",\"long\"]},{\"name\":\"callback_string\",\"type\":[\"null\",\"string\"]},{\"name\":\"campaign_id\",\"type\":[\"null\",\"long\"]},{\"name\":\"event_type\",\"type\":[\"null\",\"string\"]}]}");
  @Deprecated public Long tenant_id;
  @Deprecated public CharSequence device_id;
  @Deprecated public CharSequence device_id_type;
  @Deprecated public CharSequence device_encoding_type;
  @Deprecated public Long store_id;
  @Deprecated public Long geofence_id;
  @Deprecated public CharSequence device_date_time;
  @Deprecated public Double device_location_accuracy;
  @Deprecated public Double device_location_latitude;
  @Deprecated public Double device_location_longitude;
  @Deprecated public CharSequence request;
  @Deprecated public CharSequence response;
  @Deprecated public CharSequence requestDate;
  @Deprecated public Long message_id;
  @Deprecated public Long push_notification_event_id;
  @Deprecated public CharSequence callback_string;
  @Deprecated public Long campaign_id;
  @Deprecated public CharSequence event_type;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public Object get(int field$) {
    switch (field$) {
    case 0: return tenant_id;
    case 1: return device_id;
    case 2: return device_id_type;
    case 3: return device_encoding_type;
    case 4: return store_id;
    case 5: return geofence_id;
    case 6: return device_date_time;
    case 7: return device_location_accuracy;
    case 8: return device_location_latitude;
    case 9: return device_location_longitude;
    case 10: return request;
    case 11: return response;
    case 12: return requestDate;
    case 13: return message_id;
    case 14: return push_notification_event_id;
    case 15: return callback_string;
    case 16: return campaign_id;
    case 17: return event_type;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, Object value$) {
    switch (field$) {
    case 0: tenant_id = (Long)value$; break;
    case 1: device_id = (CharSequence)value$; break;
    case 2: device_id_type = (CharSequence)value$; break;
    case 3: device_encoding_type = (CharSequence)value$; break;
    case 4: store_id = (Long)value$; break;
    case 5: geofence_id = (Long)value$; break;
    case 6: device_date_time = (CharSequence)value$; break;
    case 7: device_location_accuracy = (Double)value$; break;
    case 8: device_location_latitude = (Double)value$; break;
    case 9: device_location_longitude = (Double)value$; break;
    case 10: request = (CharSequence)value$; break;
    case 11: response = (CharSequence)value$; break;
    case 12: requestDate = (CharSequence)value$; break;
    case 13: message_id = (Long)value$; break;
    case 14: push_notification_event_id = (Long)value$; break;
    case 15: callback_string = (CharSequence)value$; break;
    case 16: campaign_id = (Long)value$; break;
    case 17: event_type = (CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'tenant_id' field.
   */
  public Long getTenantId() {
    return tenant_id;
  }

  /**
   * Sets the value of the 'tenant_id' field.
   * @param value the value to set.
   */
  public void setTenantId(Long value) {
    this.tenant_id = value;
  }

  /**
   * Gets the value of the 'device_id' field.
   */
  public CharSequence getDeviceId() {
    return device_id;
  }

  /**
   * Sets the value of the 'device_id' field.
   * @param value the value to set.
   */
  public void setDeviceId(CharSequence value) {
    this.device_id = value;
  }

  /**
   * Gets the value of the 'device_id_type' field.
   */
  public CharSequence getDeviceIdType() {
    return device_id_type;
  }

  /**
   * Sets the value of the 'device_id_type' field.
   * @param value the value to set.
   */
  public void setDeviceIdType(CharSequence value) {
    this.device_id_type = value;
  }

  /**
   * Gets the value of the 'device_encoding_type' field.
   */
  public CharSequence getDeviceEncodingType() {
    return device_encoding_type;
  }

  /**
   * Sets the value of the 'device_encoding_type' field.
   * @param value the value to set.
   */
  public void setDeviceEncodingType(CharSequence value) {
    this.device_encoding_type = value;
  }

  /**
   * Gets the value of the 'store_id' field.
   */
  public Long getStoreId() {
    return store_id;
  }

  /**
   * Sets the value of the 'store_id' field.
   * @param value the value to set.
   */
  public void setStoreId(Long value) {
    this.store_id = value;
  }

  /**
   * Gets the value of the 'geofence_id' field.
   */
  public Long getGeofenceId() {
    return geofence_id;
  }

  /**
   * Sets the value of the 'geofence_id' field.
   * @param value the value to set.
   */
  public void setGeofenceId(Long value) {
    this.geofence_id = value;
  }

  /**
   * Gets the value of the 'device_date_time' field.
   */
  public CharSequence getDeviceDateTime() {
    return device_date_time;
  }

  /**
   * Sets the value of the 'device_date_time' field.
   * @param value the value to set.
   */
  public void setDeviceDateTime(CharSequence value) {
    this.device_date_time = value;
  }

  /**
   * Gets the value of the 'device_location_accuracy' field.
   */
  public Double getDeviceLocationAccuracy() {
    return device_location_accuracy;
  }

  /**
   * Sets the value of the 'device_location_accuracy' field.
   * @param value the value to set.
   */
  public void setDeviceLocationAccuracy(Double value) {
    this.device_location_accuracy = value;
  }

  /**
   * Gets the value of the 'device_location_latitude' field.
   */
  public Double getDeviceLocationLatitude() {
    return device_location_latitude;
  }

  /**
   * Sets the value of the 'device_location_latitude' field.
   * @param value the value to set.
   */
  public void setDeviceLocationLatitude(Double value) {
    this.device_location_latitude = value;
  }

  /**
   * Gets the value of the 'device_location_longitude' field.
   */
  public Double getDeviceLocationLongitude() {
    return device_location_longitude;
  }

  /**
   * Sets the value of the 'device_location_longitude' field.
   * @param value the value to set.
   */
  public void setDeviceLocationLongitude(Double value) {
    this.device_location_longitude = value;
  }

  /**
   * Gets the value of the 'request' field.
   */
  public CharSequence getRequest() {
    return request;
  }

  /**
   * Sets the value of the 'request' field.
   * @param value the value to set.
   */
  public void setRequest(CharSequence value) {
    this.request = value;
  }

  /**
   * Gets the value of the 'response' field.
   */
  public CharSequence getResponse() {
    return response;
  }

  /**
   * Sets the value of the 'response' field.
   * @param value the value to set.
   */
  public void setResponse(CharSequence value) {
    this.response = value;
  }

  /**
   * Gets the value of the 'requestDate' field.
   */
  public CharSequence getRequestDate() {
    return requestDate;
  }

  /**
   * Sets the value of the 'requestDate' field.
   * @param value the value to set.
   */
  public void setRequestDate(CharSequence value) {
    this.requestDate = value;
  }

  /**
   * Gets the value of the 'message_id' field.
   */
  public Long getMessageId() {
    return message_id;
  }

  /**
   * Sets the value of the 'message_id' field.
   * @param value the value to set.
   */
  public void setMessageId(Long value) {
    this.message_id = value;
  }

  /**
   * Gets the value of the 'push_notification_event_id' field.
   */
  public Long getPushNotificationEventId() {
    return push_notification_event_id;
  }

  /**
   * Sets the value of the 'push_notification_event_id' field.
   * @param value the value to set.
   */
  public void setPushNotificationEventId(Long value) {
    this.push_notification_event_id = value;
  }

  /**
   * Gets the value of the 'callback_string' field.
   */
  public CharSequence getCallbackString() {
    return callback_string;
  }

  /**
   * Sets the value of the 'callback_string' field.
   * @param value the value to set.
   */
  public void setCallbackString(CharSequence value) {
    this.callback_string = value;
  }

  /**
   * Gets the value of the 'campaign_id' field.
   */
  public Long getCampaignId() {
    return campaign_id;
  }

  /**
   * Sets the value of the 'campaign_id' field.
   * @param value the value to set.
   */
  public void setCampaignId(Long value) {
    this.campaign_id = value;
  }

  /**
   * Gets the value of the 'event_type' field.
   */
  public CharSequence getEventType() {
    return event_type;
  }

  /**
   * Sets the value of the 'event_type' field.
   * @param value the value to set.
   */
  public void setEventType(CharSequence value) {
    this.event_type = value;
  }

  /** Creates a new LocalpointEventMsgAvro RecordBuilder */
  public static Builder newBuilder() {
    return new Builder();
  }

  /** Creates a new LocalpointEventMsgAvro RecordBuilder by copying an existing Builder */
  public static Builder newBuilder(Builder other) {
    return new Builder(other);
  }

  /** Creates a new LocalpointEventMsgAvro RecordBuilder by copying an existing LocalpointEventMsgAvro instance */
  public static Builder newBuilder(LocalpointEventMsgAvro other) {
    return new Builder(other);
  }

  /**
   * RecordBuilder for LocalpointEventMsgAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LocalpointEventMsgAvro>
    implements org.apache.avro.data.RecordBuilder<LocalpointEventMsgAvro> {

    private Long tenant_id;
    private CharSequence device_id;
    private CharSequence device_id_type;
    private CharSequence device_encoding_type;
    private Long store_id;
    private Long geofence_id;
    private CharSequence device_date_time;
    private Double device_location_accuracy;
    private Double device_location_latitude;
    private Double device_location_longitude;
    private CharSequence request;
    private CharSequence response;
    private CharSequence requestDate;
    private Long message_id;
    private Long push_notification_event_id;
    private CharSequence callback_string;
    private Long campaign_id;
    private CharSequence event_type;

    /** Creates a new Builder */
    private Builder() {
      super(LocalpointEventMsgAvro.SCHEMA$);
    }

    /** Creates a Builder by copying an existing Builder */
    private Builder(Builder other) {
      super(other);
    }

    /** Creates a Builder by copying an existing LocalpointEventMsgAvro instance */
    private Builder(LocalpointEventMsgAvro other) {
            super(LocalpointEventMsgAvro.SCHEMA$);
      if (isValidValue(fields()[0], other.tenant_id)) {
        this.tenant_id = (Long) data().deepCopy(fields()[0].schema(), other.tenant_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.device_id)) {
        this.device_id = (CharSequence) data().deepCopy(fields()[1].schema(), other.device_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.device_id_type)) {
        this.device_id_type = (CharSequence) data().deepCopy(fields()[2].schema(), other.device_id_type);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.device_encoding_type)) {
        this.device_encoding_type = (CharSequence) data().deepCopy(fields()[3].schema(), other.device_encoding_type);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.store_id)) {
        this.store_id = (Long) data().deepCopy(fields()[4].schema(), other.store_id);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.geofence_id)) {
        this.geofence_id = (Long) data().deepCopy(fields()[5].schema(), other.geofence_id);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.device_date_time)) {
        this.device_date_time = (CharSequence) data().deepCopy(fields()[6].schema(), other.device_date_time);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.device_location_accuracy)) {
        this.device_location_accuracy = (Double) data().deepCopy(fields()[7].schema(), other.device_location_accuracy);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.device_location_latitude)) {
        this.device_location_latitude = (Double) data().deepCopy(fields()[8].schema(), other.device_location_latitude);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.device_location_longitude)) {
        this.device_location_longitude = (Double) data().deepCopy(fields()[9].schema(), other.device_location_longitude);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.request)) {
        this.request = (CharSequence) data().deepCopy(fields()[10].schema(), other.request);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.response)) {
        this.response = (CharSequence) data().deepCopy(fields()[11].schema(), other.response);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.requestDate)) {
        this.requestDate = (CharSequence) data().deepCopy(fields()[12].schema(), other.requestDate);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.message_id)) {
        this.message_id = (Long) data().deepCopy(fields()[13].schema(), other.message_id);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.push_notification_event_id)) {
        this.push_notification_event_id = (Long) data().deepCopy(fields()[14].schema(), other.push_notification_event_id);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.callback_string)) {
        this.callback_string = (CharSequence) data().deepCopy(fields()[15].schema(), other.callback_string);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.campaign_id)) {
        this.campaign_id = (Long) data().deepCopy(fields()[16].schema(), other.campaign_id);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.event_type)) {
        this.event_type = (CharSequence) data().deepCopy(fields()[17].schema(), other.event_type);
        fieldSetFlags()[17] = true;
      }
    }

    /** Gets the value of the 'tenant_id' field */
    public Long getTenantId() {
      return tenant_id;
    }

    /** Sets the value of the 'tenant_id' field */
    public Builder setTenantId(Long value) {
      validate(fields()[0], value);
      this.tenant_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /** Checks whether the 'tenant_id' field has been set */
    public boolean hasTenantId() {
      return fieldSetFlags()[0];
    }

    /** Clears the value of the 'tenant_id' field */
    public Builder clearTenantId() {
      tenant_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'device_id' field */
    public CharSequence getDeviceId() {
      return device_id;
    }

    /** Sets the value of the 'device_id' field */
    public Builder setDeviceId(CharSequence value) {
      validate(fields()[1], value);
      this.device_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /** Checks whether the 'device_id' field has been set */
    public boolean hasDeviceId() {
      return fieldSetFlags()[1];
    }

    /** Clears the value of the 'device_id' field */
    public Builder clearDeviceId() {
      device_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'device_id_type' field */
    public CharSequence getDeviceIdType() {
      return device_id_type;
    }

    /** Sets the value of the 'device_id_type' field */
    public Builder setDeviceIdType(CharSequence value) {
      validate(fields()[2], value);
      this.device_id_type = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /** Checks whether the 'device_id_type' field has been set */
    public boolean hasDeviceIdType() {
      return fieldSetFlags()[2];
    }

    /** Clears the value of the 'device_id_type' field */
    public Builder clearDeviceIdType() {
      device_id_type = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'device_encoding_type' field */
    public CharSequence getDeviceEncodingType() {
      return device_encoding_type;
    }

    /** Sets the value of the 'device_encoding_type' field */
    public Builder setDeviceEncodingType(CharSequence value) {
      validate(fields()[3], value);
      this.device_encoding_type = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /** Checks whether the 'device_encoding_type' field has been set */
    public boolean hasDeviceEncodingType() {
      return fieldSetFlags()[3];
    }

    /** Clears the value of the 'device_encoding_type' field */
    public Builder clearDeviceEncodingType() {
      device_encoding_type = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'store_id' field */
    public Long getStoreId() {
      return store_id;
    }

    /** Sets the value of the 'store_id' field */
    public Builder setStoreId(Long value) {
      validate(fields()[4], value);
      this.store_id = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /** Checks whether the 'store_id' field has been set */
    public boolean hasStoreId() {
      return fieldSetFlags()[4];
    }

    /** Clears the value of the 'store_id' field */
    public Builder clearStoreId() {
      store_id = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'geofence_id' field */
    public Long getGeofenceId() {
      return geofence_id;
    }

    /** Sets the value of the 'geofence_id' field */
    public Builder setGeofenceId(Long value) {
      validate(fields()[5], value);
      this.geofence_id = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /** Checks whether the 'geofence_id' field has been set */
    public boolean hasGeofenceId() {
      return fieldSetFlags()[5];
    }

    /** Clears the value of the 'geofence_id' field */
    public Builder clearGeofenceId() {
      geofence_id = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'device_date_time' field */
    public CharSequence getDeviceDateTime() {
      return device_date_time;
    }

    /** Sets the value of the 'device_date_time' field */
    public Builder setDeviceDateTime(CharSequence value) {
      validate(fields()[6], value);
      this.device_date_time = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /** Checks whether the 'device_date_time' field has been set */
    public boolean hasDeviceDateTime() {
      return fieldSetFlags()[6];
    }

    /** Clears the value of the 'device_date_time' field */
    public Builder clearDeviceDateTime() {
      device_date_time = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'device_location_accuracy' field */
    public Double getDeviceLocationAccuracy() {
      return device_location_accuracy;
    }

    /** Sets the value of the 'device_location_accuracy' field */
    public Builder setDeviceLocationAccuracy(Double value) {
      validate(fields()[7], value);
      this.device_location_accuracy = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /** Checks whether the 'device_location_accuracy' field has been set */
    public boolean hasDeviceLocationAccuracy() {
      return fieldSetFlags()[7];
    }

    /** Clears the value of the 'device_location_accuracy' field */
    public Builder clearDeviceLocationAccuracy() {
      device_location_accuracy = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'device_location_latitude' field */
    public Double getDeviceLocationLatitude() {
      return device_location_latitude;
    }

    /** Sets the value of the 'device_location_latitude' field */
    public Builder setDeviceLocationLatitude(Double value) {
      validate(fields()[8], value);
      this.device_location_latitude = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /** Checks whether the 'device_location_latitude' field has been set */
    public boolean hasDeviceLocationLatitude() {
      return fieldSetFlags()[8];
    }

    /** Clears the value of the 'device_location_latitude' field */
    public Builder clearDeviceLocationLatitude() {
      device_location_latitude = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'device_location_longitude' field */
    public Double getDeviceLocationLongitude() {
      return device_location_longitude;
    }

    /** Sets the value of the 'device_location_longitude' field */
    public Builder setDeviceLocationLongitude(Double value) {
      validate(fields()[9], value);
      this.device_location_longitude = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /** Checks whether the 'device_location_longitude' field has been set */
    public boolean hasDeviceLocationLongitude() {
      return fieldSetFlags()[9];
    }

    /** Clears the value of the 'device_location_longitude' field */
    public Builder clearDeviceLocationLongitude() {
      device_location_longitude = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'request' field */
    public CharSequence getRequest() {
      return request;
    }

    /** Sets the value of the 'request' field */
    public Builder setRequest(CharSequence value) {
      validate(fields()[10], value);
      this.request = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /** Checks whether the 'request' field has been set */
    public boolean hasRequest() {
      return fieldSetFlags()[10];
    }

    /** Clears the value of the 'request' field */
    public Builder clearRequest() {
      request = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'response' field */
    public CharSequence getResponse() {
      return response;
    }

    /** Sets the value of the 'response' field */
    public Builder setResponse(CharSequence value) {
      validate(fields()[11], value);
      this.response = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /** Checks whether the 'response' field has been set */
    public boolean hasResponse() {
      return fieldSetFlags()[11];
    }

    /** Clears the value of the 'response' field */
    public Builder clearResponse() {
      response = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'requestDate' field */
    public CharSequence getRequestDate() {
      return requestDate;
    }

    /** Sets the value of the 'requestDate' field */
    public Builder setRequestDate(CharSequence value) {
      validate(fields()[12], value);
      this.requestDate = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /** Checks whether the 'requestDate' field has been set */
    public boolean hasRequestDate() {
      return fieldSetFlags()[12];
    }

    /** Clears the value of the 'requestDate' field */
    public Builder clearRequestDate() {
      requestDate = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'message_id' field */
    public Long getMessageId() {
      return message_id;
    }

    /** Sets the value of the 'message_id' field */
    public Builder setMessageId(Long value) {
      validate(fields()[13], value);
      this.message_id = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /** Checks whether the 'message_id' field has been set */
    public boolean hasMessageId() {
      return fieldSetFlags()[13];
    }

    /** Clears the value of the 'message_id' field */
    public Builder clearMessageId() {
      message_id = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'push_notification_event_id' field */
    public Long getPushNotificationEventId() {
      return push_notification_event_id;
    }

    /** Sets the value of the 'push_notification_event_id' field */
    public Builder setPushNotificationEventId(Long value) {
      validate(fields()[14], value);
      this.push_notification_event_id = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /** Checks whether the 'push_notification_event_id' field has been set */
    public boolean hasPushNotificationEventId() {
      return fieldSetFlags()[14];
    }

    /** Clears the value of the 'push_notification_event_id' field */
    public Builder clearPushNotificationEventId() {
      push_notification_event_id = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'callback_string' field */
    public CharSequence getCallbackString() {
      return callback_string;
    }

    /** Sets the value of the 'callback_string' field */
    public Builder setCallbackString(CharSequence value) {
      validate(fields()[15], value);
      this.callback_string = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /** Checks whether the 'callback_string' field has been set */
    public boolean hasCallbackString() {
      return fieldSetFlags()[15];
    }

    /** Clears the value of the 'callback_string' field */
    public Builder clearCallbackString() {
      callback_string = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'campaign_id' field */
    public Long getCampaignId() {
      return campaign_id;
    }

    /** Sets the value of the 'campaign_id' field */
    public Builder setCampaignId(Long value) {
      validate(fields()[16], value);
      this.campaign_id = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /** Checks whether the 'campaign_id' field has been set */
    public boolean hasCampaignId() {
      return fieldSetFlags()[16];
    }

    /** Clears the value of the 'campaign_id' field */
    public Builder clearCampaignId() {
      campaign_id = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'event_type' field */
    public CharSequence getEventType() {
      return event_type;
    }

    /** Sets the value of the 'event_type' field */
    public Builder setEventType(CharSequence value) {
      validate(fields()[17], value);
      this.event_type = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /** Checks whether the 'event_type' field has been set */
    public boolean hasEventType() {
      return fieldSetFlags()[17];
    }

    /** Clears the value of the 'event_type' field */
    public Builder clearEventType() {
      event_type = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    @Override
    public LocalpointEventMsgAvro build() {
      try {
        LocalpointEventMsgAvro record = new LocalpointEventMsgAvro();
        record.tenant_id = fieldSetFlags()[0] ? this.tenant_id : (Long) defaultValue(fields()[0]);
        record.device_id = fieldSetFlags()[1] ? this.device_id : (CharSequence) defaultValue(fields()[1]);
        record.device_id_type = fieldSetFlags()[2] ? this.device_id_type : (CharSequence) defaultValue(fields()[2]);
        record.device_encoding_type = fieldSetFlags()[3] ? this.device_encoding_type : (CharSequence) defaultValue(fields()[3]);
        record.store_id = fieldSetFlags()[4] ? this.store_id : (Long) defaultValue(fields()[4]);
        record.geofence_id = fieldSetFlags()[5] ? this.geofence_id : (Long) defaultValue(fields()[5]);
        record.device_date_time = fieldSetFlags()[6] ? this.device_date_time : (CharSequence) defaultValue(fields()[6]);
        record.device_location_accuracy = fieldSetFlags()[7] ? this.device_location_accuracy : (Double) defaultValue(fields()[7]);
        record.device_location_latitude = fieldSetFlags()[8] ? this.device_location_latitude : (Double) defaultValue(fields()[8]);
        record.device_location_longitude = fieldSetFlags()[9] ? this.device_location_longitude : (Double) defaultValue(fields()[9]);
        record.request = fieldSetFlags()[10] ? this.request : (CharSequence) defaultValue(fields()[10]);
        record.response = fieldSetFlags()[11] ? this.response : (CharSequence) defaultValue(fields()[11]);
        record.requestDate = fieldSetFlags()[12] ? this.requestDate : (CharSequence) defaultValue(fields()[12]);
        record.message_id = fieldSetFlags()[13] ? this.message_id : (Long) defaultValue(fields()[13]);
        record.push_notification_event_id = fieldSetFlags()[14] ? this.push_notification_event_id : (Long) defaultValue(fields()[14]);
        record.callback_string = fieldSetFlags()[15] ? this.callback_string : (CharSequence) defaultValue(fields()[15]);
        record.campaign_id = fieldSetFlags()[16] ? this.campaign_id : (Long) defaultValue(fields()[16]);
        record.event_type = fieldSetFlags()[17] ? this.event_type : (CharSequence) defaultValue(fields()[17]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
